[env:m5stack-tab5-p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-tab5-p4
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
build_type = debug
lib_deps =
    m5stack/M5Unified

; If automatic upload detection fails, uncomment and set the COM port.
; upload_port = COM3
