[env:m5stack-tab5-p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-tab5-p4
framework = arduino
upload_speed = 1500000
monitor_speed = 1500000
build_type = release
build_flags =
  ; Uncomment to switch from USB-Serial-JTAG (HWCDC) to Native USB CDC (TinyUSB):
  ; -DARDUINO_USB_MODE=0
lib_deps =
    m5stack/M5Unified

; If automatic upload detection fails, uncomment and set the COM port.
; upload_port = COM3
